// Generated by the FlutterFire CLI — these are the real values for the
// `taskpoint-8aba0` project, the same one the mobile app (taskpoint/) uses,
// so both apps read and write one shared set of users and data.
//
// To regenerate after changing Firebase projects:
//   dart pub global activate flutterfire_cli
//   firebase login
//   flutterfire configure     # from this project's root, select "web"
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnHMemVouKj8lq4U-FfWnND5ZyA-VwJQ',
    appId: '1:871951039337:web:459cdaba9bfe3833575bf8',
    messagingSenderId: '871951039337',
    projectId: 'taskpoint-8aba0',
    authDomain: 'taskpoint-8aba0.firebaseapp.com',
    storageBucket: 'taskpoint-8aba0.firebasestorage.app',
    measurementId: 'G-3M2FC3GB05',
  );
}
